# Form implementation generated from reading ui file 'ui/newform.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 511)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.a_horizontalLayout = QtWidgets.QHBoxLayout()
        self.a_horizontalLayout.setObjectName("a_horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setMaximumSize(QtCore.QSize(240, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.a_horizontalLayout.addWidget(self.tableWidget)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Form)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.a_horizontalLayout.addWidget(self.plainTextEdit)
        self.gridLayout_2.addLayout(self.a_horizontalLayout, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.btnPlay = QtWidgets.QPushButton(parent=self.frame)
        self.btnPlay.setObjectName("btnPlay")
        self.gridLayout.addWidget(self.btnPlay, 0, 1, 1, 1)
        self.btnRandQuote = QtWidgets.QPushButton(parent=self.frame)
        self.btnRandQuote.setObjectName("btnRandQuote")
        self.gridLayout.addWidget(self.btnRandQuote, 0, 2, 1, 1)
        self.btnQuit = QtWidgets.QPushButton(parent=self.frame)
        self.btnQuit.setObjectName("btnQuit")
        self.gridLayout.addWidget(self.btnQuit, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnPlay.setText(_translate("Form", "Play"))
        self.btnRandQuote.setText(_translate("Form", "Random"))
        self.btnQuit.setText(_translate("Form", "Quit"))
